#include <gtest/gtest.h>
#include <string>
#include <sstream>
#include <fstream>
#include <vector>
#include <map>
#include "../src/PhenotypeIntegration.h"
using namespace std;

// Define a test fixture class for the Read class
class queryTermForKidsTest : public ::testing::Test
{
protected:
    void SetUp() override {}
    void TearDown() override {}
    PhenotypeIntegration phen;
};

TEST_F(queryTermForKidsTest, TestprintTermKidsTest)
{
    phen.init();
    phen.setupHPO("./HPO/HPO_release20220414/");

    // To catch the std output generated by the function

    testing::internal::CaptureStdout();
    phen.queryTermForKids("HP:0000010");
    string actual_output = testing::internal::GetCapturedStdout();
    string expected_output = " HP:0012786 HP:0012787\n";
    EXPECT_EQ(expected_output, actual_output);

    testing::internal::CaptureStdout();
    phen.queryTermForKids("HP:0000008");
    actual_output = testing::internal::GetCapturedStdout();
    expected_output = " HP:0000130 HP:0000137 HP:0000142 HP:0011027\n";
    EXPECT_EQ(expected_output, actual_output);
}
