#include <gtest/gtest.h>
#include <string>
#include <sstream>
#include <fstream>
#include <vector>
#include <map>
#include "../src/PhenotypeIntegration.h"
using namespace std;

// Define a test fixture class for the Read class
class queryTermForParTest : public ::testing::Test
{
protected:
    void SetUp() override {}
    void TearDown() override {}
    PhenotypeIntegration phen;
};

TEST_F(queryTermForParTest, TestprintTermParTest)
{
    phen.init();
    phen.setupHPO("./HPO/HPO_release20220414/");

    // To catch the std output generated by the function

    testing::internal::CaptureStdout();
    phen.queryTermForPar("HP:0000010");
    string actual_output = testing::internal::GetCapturedStdout();
    string expected_output = " HP:0002719 HP:0011277\n";
    EXPECT_EQ(expected_output, actual_output);

    testing::internal::CaptureStdout();
    phen.queryTermForPar("HP:0000008");
    actual_output = testing::internal::GetCapturedStdout();
    expected_output = " HP:0000812 HP:0010460\n";
    EXPECT_EQ(expected_output, actual_output);
}
